# Generated by Django 3.0.1 on 2020-03-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorWorker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='user_id',
            field=models.CharField(default='Test', max_length=100, unique=True),
        ),
    ]
