# Generated by Django 3.0.1 on 2020-01-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorWorker', '0004_delete_temperaturedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlowData',
        ),
        migrations.DeleteModel(
            name='PressureData',
        ),
    ]
